import randonWeighted as rdw


def age():
    age_distribution = [{'age': 18, 'percentage': 4.4},
                        {'age': 19, 'percentage': 4.4},
                        {'age': 20, 'percentage': 6.5},
                        {'age': 21, 'percentage': 4.4},
                        {'age': 22, 'percentage': 4.5},
                        {'age': 23, 'percentage': 4.0},
                        {'age': 24, 'percentage': 3.9},
                        {'age': 25, 'percentage': 3.6},
                        {'age': 26, 'percentage': 3.5},
                        {'age': 27, 'percentage': 3.5},
                        {'age': 28, 'percentage': 3.3},
                        {'age': 29, 'percentage': 3.3},
                        {'age': 30, 'percentage': 3.2},
                        {'age': 31, 'percentage': 3.0},
                        {'age': 32, 'percentage': 3.0},
                        {'age': 33, 'percentage': 2.9},
                        {'age': 34, 'percentage': 2.9},
                        {'age': 35, 'percentage': 2.8},
                        {'age': 36, 'percentage': 2.6},
                        {'age': 37, 'percentage': 2.6},
                        {'age': 38, 'percentage': 2.5},
                        {'age': 39, 'percentage': 2.5},
                        {'age': 40, 'percentage': 2.4},
                        {'age': 41, 'percentage': 2.3},
                        {'age': 42, 'percentage': 2.3},
                        {'age': 43, 'percentage': 2.2},
                        {'age': 44, 'percentage': 2.2},
                        {'age': 45, 'percentage': 2.1},
                        {'age': 46, 'percentage': 2.1},
                        {'age': 47, 'percentage': 2.1},
                        {'age': 48, 'percentage': 2.0},
                        {'age': 49, 'percentage': 2.0},
                        {'age': 50, 'percentage': 1.9},
                        {'age': 51, 'percentage': 1.9},
                        {'age': 52, 'percentage': 1.9},
                        {'age': 53, 'percentage': 1.9},
                        {'age': 54, 'percentage': 1.9},
                        {'age': 55, 'percentage': 1.8},
                        {'age': 56, 'percentage': 1.8},
                        {'age': 57, 'percentage': 1.8},
                        {'age': 58, 'percentage': 1.8},
                        {'age': 59, 'percentage': 1.8},
                        {'age': 60, 'percentage': 1.7},
                        {'age': 61, 'percentage': 1.7},
                        {'age': 62, 'percentage': 1.7},
                        {'age': 63, 'percentage': 1.7},
                        {'age': 64, 'percentage': 1.7},
                        {'age': 65, 'percentage': 1.6},
                        {'age': 66, 'percentage': 1.6},
                        {'age': 67, 'percentage': 1.6},
                        {'age': 68, 'percentage': 1.6},
                        {'age': 69, 'percentage': 1.6},
                        {'age': 70, 'percentage': 1.5},
                        {'age': 71, 'percentage': 1.5},
                        {'age': 72, 'percentage': 1.5},
                        {'age': 73, 'percentage': 1.5},
                        {'age': 74, 'percentage': 1.5},
                        {'age': 75, 'percentage': 1.4},
                        {'age': 76, 'percentage': 1.4},
                        {'age': 77, 'percentage': 1.4},
                        {'age': 78, 'percentage': 1.4},
                        {'age': 79, 'percentage': 1.4},
                        {'age': 80, 'percentage': 2.3},
                        {'age': 81, 'percentage': 2.2},
                        {'age': 82, 'percentage': 2.1},
                        {'age': 83, 'percentage': 2.0},
                        {'age': 84, 'percentage': 1.9},
                        {'age': 85, 'percentage': 3.2},
                        {'age': 86, 'percentage': 3.0},
                        {'age': 87, 'percentage': 2.8},
                        {'age': 88, 'percentage': 2.6},
                        {'age': 89, 'percentage': 2.4},
                        {'age': 90, 'percentage': 3.7},
                        {'age': 91, 'percentage': 3.3},
                        {'age': 92, 'percentage': 3.3}

                        ]

    return rdw.weighted_choice(age)
